import type { NodeDefinition } from "@loanscope/graph";

export const inputNodes: NodeDefinition[] = [
  { id: "baseLoanAmount", kind: "input", valueType: "Money" },
  {
    id: "financedUpfrontFees",
    kind: "input",
    valueType: "Boolean",
    defaultValue: false,
  },
  { id: "propertyValue", kind: "input", valueType: "Money" },
  { id: "purchasePrice", kind: "input", valueType: "Money" },
  { id: "downPayment", kind: "input", valueType: "Money" },
  { id: "fico", kind: "input", valueType: "Enum" },
  { id: "ficoScores", kind: "input", valueType: "Array" },
  { id: "noteRatePct", kind: "input", valueType: "RatePct" },
  { id: "amortizationMonths", kind: "input", valueType: "Months" },
  { id: "interestOnlyMonths", kind: "input", valueType: "Months" },
  { id: "amortizationType", kind: "input", valueType: "Enum" },
  { id: "borrowers", kind: "input", valueType: "Array" },
  { id: "monthlyIncome", kind: "input", valueType: "Money" },
  { id: "liabilities", kind: "input", valueType: "Array" },
  { id: "monthlyDebts", kind: "input", valueType: "Money" },
  { id: "assets", kind: "input", valueType: "Array" },
  { id: "totalLiquidAssets", kind: "input", valueType: "Money" },
  { id: "totalRetirementAssets", kind: "input", valueType: "Money" },
  { id: "propertyTax", kind: "input", valueType: "Money" },
  { id: "insurance", kind: "input", valueType: "Money" },
  { id: "hoa", kind: "input", valueType: "Money" },
  { id: "mi", kind: "input", valueType: "Money" },
  { id: "floodInsurance", kind: "input", valueType: "Money", defaultValue: 0 },
  { id: "annualTaxes", kind: "input", valueType: "Money" },
  { id: "annualInsurance", kind: "input", valueType: "Money" },
  { id: "loanPurpose", kind: "input", valueType: "Enum" },
  { id: "occupancy", kind: "input", valueType: "Enum" },
  { id: "propertyType", kind: "input", valueType: "Enum" },
  { id: "units", kind: "input", valueType: "Enum" },
  { id: "stateCode", kind: "input", valueType: "Enum" },
  { id: "closingCosts", kind: "input", valueType: "Money" },
  { id: "productRules", kind: "input", valueType: "Object" },
  { id: "loanLimits", kind: "input", valueType: "Object" },
  { id: "includedBorrowerIds", kind: "input", valueType: "Array" },
  { id: "payoffLiabilityIds", kind: "input", valueType: "Array" },
  {
    id: "subordinateLiens",
    kind: "input",
    valueType: "Money",
    defaultValue: 0,
  },
  { id: "reservesPolicy", kind: "input", valueType: "Object" },
  { id: "qualifyingPaymentPolicy", kind: "input", valueType: "Object" },
  { id: "maxLTVRatio", kind: "input", valueType: "Ratio" },
  { id: "maxCLTVRatio", kind: "input", valueType: "Ratio" },
  { id: "maxDTIRatio", kind: "input", valueType: "Ratio" },
  { id: "minFico", kind: "input", valueType: "Enum" },
  { id: "ficoTiers", kind: "input", valueType: "Array" },
  { id: "minLoanAmount", kind: "input", valueType: "Money" },
  { id: "maxLoanAmount", kind: "input", valueType: "Money" },
  { id: "minLoanAmountRule", kind: "input", valueType: "Enum" },
  { id: "maxLtvByOccupancy", kind: "input", valueType: "Object" },
  { id: "maxLtvByPurpose", kind: "input", valueType: "Object" },
  { id: "allowedOccupancies", kind: "input", valueType: "Array" },
  { id: "allowedPurposes", kind: "input", valueType: "Array" },
  { id: "allowedPropertyTypes", kind: "input", valueType: "Array" },
  { id: "unitsAllowed", kind: "input", valueType: "Array" },
  { id: "borrowerRestrictions", kind: "input", valueType: "Object" },
  { id: "stateIneligibility", kind: "input", valueType: "Array" },
  { id: "cashOut", kind: "input", valueType: "Object" },
  { id: "cashOutConstraints", kind: "input", valueType: "Object" },
  { id: "buydown", kind: "input", valueType: "Object" },
  { id: "buydownRules", kind: "input", valueType: "Object" },
  { id: "miSelection", kind: "input", valueType: "Object" },
  { id: "miRules", kind: "input", valueType: "Object" },
  { id: "ausFindings", kind: "input", valueType: "Object" },
  { id: "ausRules", kind: "input", valueType: "Object" },
  { id: "appraisalRules", kind: "input", valueType: "Object" },
  { id: "reservesIneligibleTypes", kind: "input", valueType: "Array" },
  { id: "loanType", kind: "input", valueType: "Enum" },
  {
    id: "vaServiceContext",
    kind: "input",
    valueType: "Object",
    defaultValue: null,
  },
  {
    id: "subjectPropertyRental",
    kind: "input",
    valueType: "Object",
    defaultValue: null,
  },
  {
    id: "borrowerBlendPolicy",
    kind: "input",
    valueType: "Object",
    defaultValue: null,
  },
  {
    id: "incomePolicies",
    kind: "input",
    valueType: "Object",
    defaultValue: null,
  },
];
